name: Build and Release

on:
    workflow_dispatch:

env:
    VERSION: 0.1.0

jobs:
    # Release build job
    release:
        permissions: write-all
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, macos-13, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential curl libssl-dev

            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2

            - name: Install app dependencies
              run: cargo install cargo-packager --locked

            - name: Package Binary
              run: cargo packager --release --verbose

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.platform }}-release-artifacts
                  path: |
                      ${{ matrix.platform == 'macos-latest' && 'target/release/SlightlyBetterText_*_aarch64.dmg' || '' }}
                      ${{ matrix.platform == 'macos-13' && 'target/release/SlightlyBetterText_*_x64.dmg' || '' }}
                      ${{ matrix.platform == 'ubuntu-latest' && 'target/release/PKGBUILD' || '' }}
                      ${{ matrix.platform == 'ubuntu-latest' && 'target/release/slightlybettertext_*_amd64.deb' || '' }}
                      ${{ matrix.platform == 'ubuntu-latest' && 'target/release/slightlybettertext_*_x86_64.AppImage' || '' }}
                      ${{ matrix.platform == 'windows-latest' && 'target/release/slightlybettertext_*_x64_en-US.msi' || '' }}
                      ${{ matrix.platform == 'windows-latest' && 'target/release/slightlybettertext_*_x64-setup.exe' || '' }}

    # Upload to GitHub release job
    upload_to_release:
        permissions: write-all
        runs-on: ubuntu-latest
        needs: release
        steps:
            - name: Download release artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts
                  merge-multiple: true

            - name: Create attestation for all builds
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: |
                      artifacts/PKGBUILD
                      artifacts/SlightlyBetterText_*_aarch64.dmg
                      artifacts/SlightlyBetterText_*_x64.dmg
                      artifacts/slightlybettertext_*_amd64.deb
                      artifacts/slightlybettertext_*_x86_64.AppImage
                      artifacts/slightlybettertext_*_x64_en-US.msi
                      artifacts/slightlybettertext_*_x64-setup.exe

            - name: Release to GitHub
              uses: softprops/action-gh-release@v2
              with:
                  draft: true
                  generate_release_notes: true
                  tag_name: SlightlyBetterText v${{ env.VERSION }}
                  files: |
                      artifacts/PKGBUILD
                      artifacts/SlightlyBetterText_*_aarch64.dmg
                      artifacts/SlightlyBetterText_*_x64.dmg
                      artifacts/slightlybettertext_*_amd64.deb
                      artifacts/slightlybettertext_*_x86_64.AppImage
                      artifacts/slightlybettertext_*_x64_en-US.msi
                      artifacts/slightlybettertext_*_x64-setup.exe
